name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      OMSCENTRAL_ENV: 'github'
      CI: true
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install GraphQL
        run: npm run install:graphql
      - name: Build GraphQL
        run: npm run build:graphql
      - name: Install Client
        run: npm run install:client
      - name: Build Client
        run: npm run build:client
      - name: Test Client
        run: npm run test:client
      - name: Deploy Client
        run: cd client && npm run firebase deploy -- --only hosting --message "${GITHUB_SHA}" --project omscentral-production
